### ISSUE TITLE
Axios timeout errors

### ISSUE THREAD

**Issue by milouk** [manuc66/node-hp-scan-to#809]
**Describe the bug**

First of all what such great work youve done here! Thank you for this!

Device: HP Deskjet 5525
Command line or Docker :

My Docker Config is:

```
hp-scan:
    <<: *common-keys-core
    container_name: hp-scan
    image: manuc66/node-hp-scan-to:latest
    hostname: orion
    dns:
      - 10.1.0.6
    environment:
      - S6_CMD_WAIT_FOR_SERVICES_MAXTIME=0
      - IP=192.168.10.129
      - LABEL=orion
      - PATTERN="scan"_dd.mm.yyyy_hh:MM:ss
      - PGID=0
      - PUID=0
      - TZ=Europe/Athens
    volumes:
      - /mnt/files/scan:/scan
    networks:
      private-network:
        ipv4_address: 10.1.0.28
    labels:
      - com.centurylinklabs.watchtower.enable=true
```

So after the container runs for some hours these errors popup:

```
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/10-adduser

User uid:    0
User gid:    0
-------------------------------------

cont-init: info: /etc/cont-init.d/10-adduser exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
Starting
WARNING: NODE_ENV value of 'production' did not match any deployment config file names.
WARNING: See https://github.com/node-config/node-config/wiki/Strict-Mode
WARNING: No configurations found in configuration directory:/app/config
WARNING: To disable this warning set SUPPRESS_NO_CONFIG_WARNING in the environment.
Using device ip: 192.168.10.129
Target folder: /scan
Temp folder: /tmp/scan-to-pcJlMFDp
Running iteration: 0 - errorCount: 0
Host destinations fetched: orion
Re-using existing destination: orion - /WalkupScanToComp/WalkupScanToCompDestinations/1c8532ee-b824-1f08-9fba-2c59e5ac3dc1
Using: orion
Waiting scan event for: /WalkupScanToComp/WalkupScanToCompDestinations/1c8532ee-b824-1f08-9fba-2c59e5ac3dc1
Start listening for new ScanEvent
AxiosError: timeout of 132000ms exceeded
    at RedirectableRequest.handleRequestTimeout (/app/node_modules/axios/dist/node/axios.cjs:3120:16)
    at RedirectableRequest.emit (node:events:517:28)
    at Timeout.<anonymous> (/app/node_modules/follow-redirects/index.js:179:12)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7) {
  code: 'ECONNABORTED',
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [ 'xhr', 'http' ],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 132000,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    env: { FormData: [Function], Blob: [class Blob] },
    validateStatus: [Function: validateStatus],
    headers: Object [AxiosHeaders] {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': undefined,
      'If-None-Match': '"1514-77"',
      'User-Agent': 'axios/1.6.2',
      'Accept-Encoding': 'gzip, compress, deflate, br'
    },
    baseURL: 'http://192.168.10.129',
    url: '/EventMgmt/EventTable?timeout=1200',
    method: 'get',
    responseType: 'text',
    data: undefined
  },
  request: <ref *1> Writable {
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: false,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      destroyed: false,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: true,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      afterWriteTickInfo: null,
      buffered: [],
      bufferedIndex: 0,
      allBuffers: true,
      allNoop: true,
      pendingcb: 0,
      constructed: true,
      prefinished: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: true,
      errored: null,
      closed: false,
      closeEmitted: false,
      [Symbol(kOnFinished)]: []
    },
    _events: [Object: null prototype] {
      response: [Function: handleResponse],
      error: [Function: handleRequestError],
      socket: [Array]
    },
    _eventsCount: 3,
    _maxListeners: undefined,
    _options: {
      maxRedirects: 21,
      maxBodyLength: Infinity,
      protocol: 'http:',
      path: '/EventMgmt/EventTable?timeout=1200',
      method: 'GET',
      headers: [Object: null prototype],
      agents: [Object],
      auth: undefined,
      family: undefined,
      beforeRedirect: [Function: dispatchBeforeRedirect],
      beforeRedirects: [Object],
      hostname: '192.168.10.129',
      port: '',
      agent: undefined,
      nativeProtocols: [Object],
      pathname: '/EventMgmt/EventTable',
      search: '?timeout=1200'
    },
    _ended: true,
    _ending: true,
    _redirectCount: 0,
    _redirects: [],
    _requestBodyLength: 0,
    _requestBodyBuffers: [],
    _onNativeResponse: [Function (anonymous)],
    _currentRequest: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      strictContentLength: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: false,
      socket: [Socket],
      _header: 'GET /EventMgmt/EventTable?timeout=1200 HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'If-None-Match: "1514-77"\r\n' +
        'User-Agent: axios/1.6.2\r\n' +
        'Accept-Encoding: gzip, compress, deflate, br\r\n' +
        'Host: 192.168.10.129\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      joinDuplicateHeaders: undefined,
      path: '/EventMgmt/EventTable?timeout=1200',
      _ended: false,
      res: null,
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: [HTTPParser],
      maxHeadersCount: null,
      reusedSocket: false,
      host: '192.168.10.129',
      protocol: 'http:',
      _redirectable: [Circular *1],
      [Symbol(kCapture)]: false,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype],
      [Symbol(errored)]: null,
      [Symbol(kHighWaterMark)]: 16384,
      [Symbol(kRejectNonStandardBodyWrites)]: false,
      [Symbol(kUniqueHeaders)]: null
    },
    _currentUrl: 'http://192.168.10.129/EventMgmt/EventTable?timeout=1200',
    _timeout: null,
    [Symbol(kCapture)]: false
  }
}
Device ip: 192.168.10.129 is down! [2023-12-02T09:53:36.383Z]
Device ip: 192.168.10.129 is up again! [2023-12-02T09:55:43.372Z]
Running iteration: 0 - errorCount: 0
Host destinations fetched: orion
Re-using existing destination: orion - /WalkupScanToComp/WalkupScanToCompDestinations/1c8532ee-b824-1f08-9fba-2c59e5ac3dc1
Using: orion
Waiting scan event for: /WalkupScanToComp/WalkupScanToCompDestinations/1c8532ee-b824-1f08-9fba-2c59e5ac3dc1
Start listening for new ScanEvent
Scan event captured, saving scan #0
Selected shortcut: SaveDocument1
Scan will be converted to pdf, using /tmp/scan-to-pcJlMFDp as temp scan output directory for individual pages
ScanPlexMode is : Simplex
Afd is :
New job created: http://192.168.10.129:8080/Jobs/JobList/15
Ready to download page job page 1 at: /Scan/Jobs/15/Pages/1
Page downloaded to: /tmp/scan-to-pcJlMFDp/37can.jpg
Job state: Completed, totalPages: 1:
Start listening for new ScanEvent
New job created: http://192.168.10.129:8080/Jobs/JobList/16
Ready to download page job page 1 at: /Scan/Jobs/16/Pages/1
Page downloaded to: /tmp/scan-to-pcJlMFDp/10can.jpg
Job state: Completed, totalPages: 2:
Start listening for new ScanEvent
Scan of page(s) completed totalPages: 2:
The following page(s) have been rendered inside '/scan/15can.pdf':
	- page   1 - 1654x2338
	- page   2 - 1654x2338
Running iteration: 0 - errorCount: 0
Host destinations fetched: orion
Re-using existing destination: orion - /WalkupScanToComp/WalkupScanToCompDestinations/1c8532ee-b824-1f08-9fba-2c59e5ac3dc1
Using: orion
Waiting scan event for: /WalkupScanToComp/WalkupScanToCompDestinations/1c8532ee-b824-1f08-9fba-2c59e5ac3dc1
Start listening for new ScanEvent
```

Please attach the output with debug (-D switch, see documentation)

**Comment by manuc66** [comment]
Hi @milouk 

Thanks for reporting the issue, it seems your device has ceased to be accessible from the network while waiting interaction a bit before 2023-12-02T09:53:36.383Z.

The log isn't pleasant, but I don't perceive any misbehavior if the device becomes inaccessible and then becomes available again.

Is there anything that you feel should be improved ?
