### ISSUE TITLE
Add Samsung/HP C480W support

### ISSUE THREAD

**Issue by filipfigzalski** [manuc66/node-hp-scan-to#965]
**Describe the bug**
Device: `Samsung/HP C480W`
Command line: `node-hp-scan-to -ip 192.168.100.10`

Whenever I try to connect to my scanner it produces following output:
<details>
<summary>output</summary>

```
Using device ip: 192.168.100.10
Target folder: /tmp/scan-to-pcXXXXXXcWKgw0
Temp folder: /tmp/scan-to-pcXXXXXXYhRBov
AxiosError: Request failed with status code 404
    at settle (/usr/lib/node_modules/node-hp-scan-to/node_modules/axios/dist/node/axios.cjs:2015:12)
    at IncomingMessage.handleStreamEnd (/usr/lib/node_modules/node-hp-scan-to/node_modules/axios/dist/node/axios.cjs:3131:11)
    at IncomingMessage.emit (node:events:531:35)
    at endReadableNT (node:internal/streams/readable:1696:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
    at Axios.request (/usr/lib/node_modules/node-hp-scan-to/node_modules/axios/dist/node/axios.cjs:4262:41)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async HPApi.callAxios (/usr/lib/node_modules/node-hp-scan-to/dist/HPApi.js:75:30)
    at async HPApi.getDiscoveryTree (/usr/lib/node_modules/node-hp-scan-to/dist/HPApi.js:129:26)
    at async readDeviceCapabilities (/usr/lib/node_modules/node-hp-scan-to/dist/readDeviceCapabilities.js:10:27)
    at async listenCmd (/usr/lib/node_modules/node-hp-scan-to/dist/index.js:27:32)
    at async Command.<anonymous> (/usr/lib/node_modules/node-hp-scan-to/dist/index.js:211:9)
    at async Command.parseAsync (/usr/lib/node_modules/node-hp-scan-to/node_modules/commander/lib/command.js:936:5)
    at async main (/usr/lib/node_modules/node-hp-scan-to/dist/index.js:251:5) {
  code: 'ERR_BAD_REQUEST',
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [ 'xhr', 'http', 'fetch' ],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    env: { FormData: [Function], Blob: [class Blob] },
    validateStatus: [Function: validateStatus],
    headers: Object [AxiosHeaders] {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': undefined,
      'User-Agent': 'axios/1.7.4',
      'Accept-Encoding': 'gzip, compress, deflate, br'
    },
    baseURL: 'http://192.168.100.10',
    url: '/DevMgmt/DiscoveryTree.xml',
    method: 'get',
    responseType: 'text',
    data: undefined
  },
  request: <ref *1> ClientRequest {
    _events: [Object: null prototype] {
      abort: [Function (anonymous)],
      aborted: [Function (anonymous)],
      connect: [Function (anonymous)],
      error: [Function (anonymous)],
      socket: [Function (anonymous)],
      timeout: [Function (anonymous)],
      finish: [Function: requestOnFinish]
    },
    _eventsCount: 7,
    _maxListeners: undefined,
    outputData: [],
    outputSize: 0,
    writable: true,
    destroyed: false,
    _last: true,
    chunkedEncoding: false,
    shouldKeepAlive: false,
    maxRequestsOnConnectionReached: false,
    _defaultKeepAlive: true,
    useChunkedEncodingByDefault: false,
    sendDate: false,
    _removedConnection: false,
    _removedContLen: false,
    _removedTE: false,
    strictContentLength: false,
    _contentLength: 0,
    _hasBody: true,
    _trailer: '',
    finished: true,
    _headerSent: true,
    _closed: false,
    socket: Socket {
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: null,
      _closeAfterHandlingError: false,
      _events: [Object],
      _readableState: [ReadableState],
      _writableState: [WritableState],
      allowHalfOpen: false,
      _maxListeners: undefined,
      _eventsCount: 7,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: null,
      _server: null,
      timeout: 5000,
      parser: null,
      _httpMessage: [Circular *1],
      [Symbol(async_id_symbol)]: 17,
      [Symbol(kHandle)]: [TCP],
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: Timeout {
        _idleTimeout: 5000,
        _idlePrev: [TimersList],
        _idleNext: [TimersList],
        _idleStart: 401,
        _onTimeout: [Function: bound ],
        _timerArgs: undefined,
        _repeat: null,
        _destroyed: false,
        [Symbol(refed)]: false,
        [Symbol(kHasPrimitive)]: false,
        [Symbol(asyncId)]: 16,
        [Symbol(triggerId)]: 0
      },
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(shapeMode)]: true,
      [Symbol(kCapture)]: false,
      [Symbol(kSetNoDelay)]: true,
      [Symbol(kSetKeepAlive)]: true,
      [Symbol(kSetKeepAliveInitialDelay)]: 60,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0
    },
    _header: 'GET /DevMgmt/DiscoveryTree.xml HTTP/1.1\r\n' +
      'Accept: application/json, text/plain, */*\r\n' +
      'User-Agent: axios/1.7.4\r\n' +
      'Accept-Encoding: gzip, compress, deflate, br\r\n' +
      'Host: 192.168.100.10\r\n' +
      'Connection: keep-alive\r\n' +
      '\r\n',
    _keepAliveTimeout: 0,
    _onPendingData: [Function: nop],
    agent: Agent {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      defaultPort: 80,
      protocol: 'http:',
      options: [Object: null prototype],
      requests: [Object: null prototype] {},
      sockets: [Object: null prototype],
      freeSockets: [Object: null prototype] {},
      keepAliveMsecs: 1000,
      keepAlive: true,
      maxSockets: Infinity,
      maxFreeSockets: 256,
      scheduling: 'lifo',
      maxTotalSockets: Infinity,
      totalSocketCount: 1,
      [Symbol(shapeMode)]: false,
      [Symbol(kCapture)]: false
    },
    socketPath: undefined,
    method: 'GET',
    maxHeaderSize: undefined,
    insecureHTTPParser: undefined,
    joinDuplicateHeaders: undefined,
    path: '/DevMgmt/DiscoveryTree.xml',
    _ended: true,
    res: IncomingMessage {
      _events: [Object],
      _readableState: [ReadableState],
      _maxListeners: undefined,
      socket: [Socket],
      httpVersionMajor: 1,
      httpVersionMinor: 1,
      httpVersion: '1.1',
      complete: true,
      rawHeaders: [Array],
      rawTrailers: [],
      joinDuplicateHeaders: undefined,
      aborted: false,
      upgrade: false,
      url: '',
      method: null,
      statusCode: 404,
      statusMessage: 'Not Found',
      client: [Socket],
      _consuming: false,
      _dumped: false,
      req: [Circular *1],
      _eventsCount: 4,
      responseUrl: 'http://192.168.100.10/DevMgmt/DiscoveryTree.xml',
      redirects: [],
      [Symbol(shapeMode)]: true,
      [Symbol(kCapture)]: false,
      [Symbol(kHeaders)]: [Object],
      [Symbol(kHeadersCount)]: 8,
      [Symbol(kTrailers)]: null,
      [Symbol(kTrailersCount)]: 0
    },
    aborted: false,
    timeoutCb: [Function: emitRequestTimeout],
    upgradeOrConnect: false,
    parser: null,
    maxHeadersCount: null,
    reusedSocket: false,
    host: '192.168.100.10',
    protocol: 'http:',
    _redirectable: Writable {
      _events: [Object],
      _writableState: [WritableState],
      _maxListeners: undefined,
      _options: [Object],
      _ended: true,
      _ending: true,
      _redirectCount: 0,
      _redirects: [],
      _requestBodyLength: 0,
      _requestBodyBuffers: [],
      _eventsCount: 3,
      _onNativeResponse: [Function (anonymous)],
      _currentRequest: [Circular *1],
      _currentUrl: 'http://192.168.100.10/DevMgmt/DiscoveryTree.xml',
      [Symbol(shapeMode)]: true,
      [Symbol(kCapture)]: false
    },
    [Symbol(shapeMode)]: false,
    [Symbol(kCapture)]: false,
    [Symbol(kBytesWritten)]: 0,
    [Symbol(kNeedDrain)]: false,
    [Symbol(corked)]: 0,
    [Symbol(kOutHeaders)]: [Object: null prototype] {
      accept: [Array],
      'user-agent': [Array],
      'accept-encoding': [Array],
      host: [Array]
    },
    [Symbol(errored)]: null,
    [Symbol(kHighWaterMark)]: 16384,
    [Symbol(kRejectNonStandardBodyWrites)]: false,
    [Symbol(kUniqueHeaders)]: null
  },
  response: {
    status: 404,
    statusText: 'Not Found',
    headers: Object [AxiosHeaders] {
      connection: 'close',
      'content-type': 'text/html',
      'content-length': '262',
      'cache-control': 'max-age=0, no-store, no-cache'
    },
    config: {
      transitional: [Object],
      adapter: [Array],
      transformRequest: [Array],
      transformResponse: [Array],
      timeout: 0,
      xsrfCookieName: 'XSRF-TOKEN',
      xsrfHeaderName: 'X-XSRF-TOKEN',
      maxContentLength: -1,
      maxBodyLength: -1,
      env: [Object],
      validateStatus: [Function: validateStatus],
      headers: [Object [AxiosHeaders]],
      baseURL: 'http://192.168.100.10',
      url: '/DevMgmt/DiscoveryTree.xml',
      method: 'get',
      responseType: 'text',
      data: undefined
    },
    request: <ref *1> ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      strictContentLength: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: false,
      socket: [Socket],
      _header: 'GET /DevMgmt/DiscoveryTree.xml HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'User-Agent: axios/1.7.4\r\n' +
        'Accept-Encoding: gzip, compress, deflate, br\r\n' +
        'Host: 192.168.100.10\r\n' +
        'Connection: keep-alive\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      joinDuplicateHeaders: undefined,
      path: '/DevMgmt/DiscoveryTree.xml',
      _ended: true,
      res: [IncomingMessage],
      aborted: false,
      timeoutCb: [Function: emitRequestTimeout],
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: '192.168.100.10',
      protocol: 'http:',
      _redirectable: [Writable],
      [Symbol(shapeMode)]: false,
      [Symbol(kCapture)]: false,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype],
      [Symbol(errored)]: null,
      [Symbol(kHighWaterMark)]: 16384,
      [Symbol(kRejectNonStandardBodyWrites)]: false,
      [Symbol(kUniqueHeaders)]: null
    },
    data: '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2//EN">\n' +
      '<HTML>\n' +
      '<HEAD>\n' +
      '<TITLE>Invalid Request</TITLE>\n' +
      '</HEAD>\n' +
      '\n' +
      '<BODY BGCOLOR="#FFFFFF" TEXT="#000000">\n' +
      '<CENTER>\n' +
      '<FONT SIZE="+2" COLOR="#FFFFFF" ALIGN="Center">\n' +
      '</FONT>\n' +
      '<B>Invalid Request. Some Error</B>\n' +
      '</BODY>\n' +
      '\n' +
      '</HTML>\n' +
      '\n'
  }
}
```
</details>

Using wireshark I was able to find out that windows "scan to pc" software is talking to `/IDS/CAP.XML`. And when I try to access this path I get following output:

<details>
<summary>XML output</summary>

```xml

<?xml version="1.0" encoding="UTF-8"?>
<root>
	<DeviceCapability>
		<ProductInfo>
			<ModelName>Samsung C48x Series</ModelName>
			<MDL>C48x Series</MDL>
			<Company>Samsung Electronics Co., Ltd.</Company>
			<Vid>04e8</Vid>
			<Pid>347e</Pid>
		</ProductInfo>
		<HardwareInfo>
			<Color>
				<Black name="SEC_Black" LongID="B_TONER_ID_LONG" ShortID="K_TONER_ID_SHORT"/>
				<Cyan name="SEC_Cyan" LongID="C_TONER_ID_LONG" ShortID="C_TONER_ID_SHORT"/>
				<Magenta name="SEC_Magenta" LongID="M_TONER_ID_LONG" ShortID="M_TONER_ID_SHORT"/>
				<Yellow name="SEC_Yellow" LongID="Y_TONER_ID_LONG" ShortID="Y_TONER_ID_SHORT"/>
			</Color>
			<Print type="Laser" />
			<Scan></Scan>
			<IOChannel>
				<USB></USB>
				<NETWORK></NETWORK>
			</IOChannel>
			<TraySpec AvailableNumberofTray="1">
				<Tray TrayID="Tray1" />
			</TraySpec>
		</HardwareInfo>
		<SoftwareInterfaceInfo>
			<UI>
				<SupportedLanguage>
					<Language ID="GR" String="German" isSupported="TRUE" />
					<Language ID="FN" String="French" isSupported="TRUE" />
					<Language ID="IT" String="Italian" isSupported="TRUE" />
					<Language ID="SP" String="Spanish" isSupported="TRUE" />
					<Language ID="RU" String="Russian" isSupported="TRUE" />
					<Language ID="PT" String="Portugal Portuguese" isSupported="TRUE" />
					<Language ID="BT" String="Brazilian Portuguese" isSupported="TRUE" />
					<Language ID="DN" String="Danish" isSupported="TRUE" />
					<Language ID="FI" String="Finnish" isSupported="TRUE" />
					<Language ID="SW" String="Swedish" isSupported="TRUE" />
					<Language ID="NR" String="Norwegian" isSupported="TRUE" />
					<Language ID="DT" String="Dutch" isSupported="TRUE" />
					<Language ID="PO" String="Polish" isSupported="TRUE" />
					<Language ID="CZ" String="Czech" isSupported="TRUE" />
					<Language ID="HU" String="Hungarian" isSupported="TRUE" />
					<Language ID="TK" String="Turkish" isSupported="TRUE" />
					<Language ID="HB" String="Hubrew" isSupported="FALSE" />
				</SupportedLanguage>
			</UI>
			<Scan2PC InterfaceVersion="2.1">
				<Scan2PCInfo>
					<SupportedPort>
						<USB />
						<Network />
					</SupportedPort>
					<MaxUser Value="10" />
					<MaxUserIDLength Value="31" />
					<MaxUserPINLength Value="32" />
					<MaxUserGUIDLength Value="16" />
					<MaxProfileNo Value="20" />
					<MaxProfileNameLength Value="30" />
					<TimeOut Value="1800" />
					<UIType Value="LCD" />
					<HTTPURL>
						<POST Value="/IDS/ScanFaxToPC.cgi"/>
						<GET Value="/IDS/UserSelect.xml"/>
					</HTTPURL>
					<ScannerType Value="FLATBED"/>
					<ScanMethod Value="Light SSIP" />
					<TransferDataType Value="Processed_IMG" />
					<ScanSize DefaultValue="SIZE_A4">
						<Size ID="SIZE_A4" STRING="A4"/>
						<Size ID="SIZE_A5" STRING="A5"/>
						<Size ID="SIZE_B5_JIS" STRING="B5(JIS)"/>
						<Size ID="SIZE_EXECUTIVE" STRING="Executive"/>
						<Size ID="SIZE_LETTER" STRING="Letter"/>
					</ScanSize>
					<FileFormat DefaultValue="FORMAT_M_PDF">
						<Format ID="FORMAT_JPEG" STRING="JPEG"/>
						<Format ID="FORMAT_S_TIFF" STRING="Single page TIFF"/>
						<Format ID="FORMAT_M_TIFF" STRING="Multi page TIFF"/>
						<Format ID="FORMAT_S_PDF" STRING="Single page PDF"/>
						<Format ID="FORMAT_M_PDF" STRING="Multi page PDF"/>
					</FileFormat>
					<ScanColor>
						<Color ID="COLOR_TRUE" STRING="Color"/>
						<Color ID="COLOR_GRAY" STRING="Gray"/>
						<Color ID="COLOR_MONO" STRING="Mono"/>
					</ScanColor>
					<ScanResolution DefaultValue="DPI_300">
						<Resolution ID="DPI_100" STRING="100 dpi"/>
						<Resolution ID="DPI_200" STRING="200 dpi"/>
						<Resolution ID="DPI_300" STRING="300 dpi"/>
						<Resolution ID="DPI_600" STRING="600 dpi"/>
					</ScanResolution>
					<OriginalType DefaultValue="ORIGINTYPE_TEXT">
						<Type ID="ORIGINTYPE_TEXT" STRING="Text"/>
						<Type ID="ORIGINTYPE_TEXT_PHOTO" STRING="Text/Photo"/>
						<Type ID="ORIGINTYPE_PHOTO" STRING="Photo"/>
					</OriginalType>
					<FileName IsSettableByHost="FALSE" IsGettableFromDevice="FALSE"/>
					<Darkness  DefaultValue="DARKNESS_NORMAL" >
						<Darkness ID="DARKNESS_LIGHT5" STRING="Light+5" />
						<Darkness ID="DARKNESS_LIGHT4" STRING="Light+4" />
						<Darkness ID="DARKNESS_LIGHT3" STRING="Light+3" />
						<Darkness ID="DARKNESS_LIGHT2" STRING="Light+2" />
						<Darkness ID="DARKNESS_LIGHT1" STRING="Light+1" />
						<Darkness ID="DARKNESS_NORMAL" STRING="Normal" />
						<Darkness ID="DARKNESS_DARK1" STRING="Dark+1" />
						<Darkness ID="DARKNESS_DARK2" STRING="Dark+2" />
						<Darkness ID="DARKNESS_DARK3" STRING="Dark+3" />
						<Darkness ID="DARKNESS_DARK4" STRING="Dark+4" />
						<Darkness ID="DARKNESS_DARK5" STRING="Dark+5" /></Darkness>
				</Scan2PCInfo>
				<Dependencies>
					<ScanColor>
						<Hide>
							<Condition>
								<FileFormat CURRENT="FORMAT_JPEG"/>
							</Condition>
							<Value>
								<COLOR_MONO/>
							</Value>
						</Hide>
					</ScanColor>
					<ScanResolution>
						<Hide>
							<Condition>
								<Color CURRENT="COLOR_TRUE"/>
							</Condition>
							<Condition>
								<Color CURRENT="COLOR_GRAY"/>
							</Condition>
							<Value>
								<DPI_600/>
							</Value>
						</Hide>
					</ScanResolution>
				</Dependencies>
			</Scan2PC>
			<IDSAlert InterfaceVersion="1.0">
				<NETWORK URL="http://192.168.100.10/SmartPanel/sm.xml"/>
				<USB></USB>
			</IDSAlert>
			<PSU InterfaceVersion="1.0">
				<NETWORK isSWSLink="TRUE"/>
				<USB></USB>
			</PSU>
			<AutoConfiguration InterfaceUpdate="2010.08.05">
				<NETWORK Support="TRUE"/>
				<USB Support="TRUE" CheckMethod="ExtentionDeviceID" CheckString="ALL" NotSupportResponse="NOTSPPRT"/>
			</AutoConfiguration>
			<RebootAfterFMU Required="0" MaxTimeOut="60000"></RebootAfterFMU>
			<FMU_RESPONSE Support="TRUE"></FMU_RESPONSE>
		</SoftwareInterfaceInfo>
	</DeviceCapability>
</root>
```
</details>

Is it possible to make this software work with this printer?

**Comment by manuc66** [comment]
Hello,

Thank you for reaching out. Unfortunately, the printer you are using is not supported by this project as it behaves more like a Samsung printer rather than an HP printer. None of the HTTP resources match with those supported by this project.

However, based on the information you provided, I have identified a few projects that might be helpful for you:
- [Samsung ScanToPC](https://github.com/kleest/samsung-scantopc) - A tool to interact with the "Scan to PC" option in Samsung MFP.
- [Scand](https://github.com/brunoga/scand) - A send-to-email scanner daemon for Samsung network printers.
- [Scan to PC in Linux (Development)](https://www.bchemnet.com/suldr/forum/index.php?topic=391.0) - A forum discussion on scanning to PC in Linux.

I hope these resources will be useful for your needs.

Best regards,

**Comment by filipfigzalski** [comment]
Thank you very much for the links. Since all the support pages are on hp website I was hoping it would be possible to use HP software.

Best regards
